apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/mi-albr/argocd-workshop.git'
    path: applications/overlays/dev
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
