apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-repo/argo-cd-app-of-apps-example.git'
    path: apps/external-kustomize-app/base
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
