apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app-prod
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: nginx
    targetRevision: 8.9.1
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  plugin:
    name: argocd-lovely-plugin
    parameters:
      - name: "extraResources"
        value: "extra-resources/configmap.yaml,extra-resources/secret.yaml"
